### ISSUE TITLE
Setup automation jobs

### ISSUE THREAD

**Issue by mattcarabine** [couchbaselabs/docs-style-guide#8]
Need the following:
- [x] Job to build the 4.5 docs on change
- [x] Job to build the master docs on change
- [x] Job to build the mobile docs
- [x] Job to push the 4.5 or master docs to the external jenkins draft site
- [x] Extend the draft jobs to identify which pages have changed in each build
- [x] Serve the draft sites via a proper web proxy like nginx or apache rather than individual python http servers.

**Comment by mattcarabine** [comment]
Need to fix the mobile docs as the jekyll building does not seem to be working properly.

**Comment by tleyden** [comment]
FWIW [this jenkins job](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/configure) clones from a private github repo.

In the config, there is a private key defined in the passwords section, and in the shell script:

```
# Enable building private sync-gateway-accel repo by making sure that 
# the VM's have the private key that is registered with github as a 
# deploy key on the sync-gateway-accel repo
echo $private_key_base64 | base64 -d > /tmp/private_key
python libraries/utilities/install-gh-deploy-keys.py \
    --key-path=/tmp/private_key \
    --ssh-user=root
```

Now all the VM's will have the private key.

I believe the private key was created by creating a "Github Deploy Key" on the github website, and it only has read-only permissions.

**Comment by mattcarabine** [comment]
I don't think the private repos are an issue in this case. I've provided an ssh key to use to update all submodules.
