### ISSUE TITLE
Pairing session 2

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/docs-style-guide#9]
@mattcarabine & @jamiltz's todos:

- [x] Move swagger resources to docs' s3
- [x] Fix error `jquery.js:5 Uncaught Error: Syntax error, unrecognized expression: #!/attachment(…)` when clicking an endpoint on [embedded swagger ui](http://developer.couchbase.com/documentation/mobile/1.3/references/sync-gateway/rest-api/index.html#/attachment)
- [x] Make the "Try it out" optional. For interfaces that don't support CORS (SG Admin) it should display an example curl request by default.
- [ ] Try to write a dita plugin to improve the local preview of docs (see [feature/templatize_live_site](https://github.com/couchbaselabs/couchbase-mobile-portal/compare/feature/templatize_live_site) to get the wrapping divs, scripts, styles tags)

**Comment by mattcarabine** [comment]
I have already moved the files to the s3 bucket cb-swagger.

What we'll need to do is migrate the content of the web pages and the jenkins job to point to the new location.
